from flask import Flask, request, jsonify, make_response, send_file
import json
import time
import os
import tempfile
from pathlib import Path
import uuid
from datetime import datetime

app = Flask(__name__)

# Mock printer state
class MockPrinter:
    def __init__(self, ip="127.0.0.1"):
        self.ip = ip
        self.sessions = {}  # session_id -> user_info
        self.jobs = {}  # job_id -> job_info
        self.address_book = []
        self.exported_files = {}  # token -> file_path
        self.h_tokens = {}  # session_id -> token
        self.load_default_address_book()
    
    def load_default_address_book(self):
        """Load some sample address book entries"""
        self.address_book = [
            {
                "AbbrNo": "1",
                "Name": "test.user1",
                "SendMode": "Smb",
                "SMBAddress": "192.168.1.100",
                "SMBFolder": r"\servicePath\test.user1",
                "SMBLoginUser": "smb_user",
                "SMBLoginPassword": "[CONV]smb_pass",
                "SearchKey": "Tuv",
                "UseReferLicence": "Level",
                "ReferGroupNo": "0",
                "ReferPossibleLevel": "0",
                "WellUse": "No",
                "Pinyin": "No"
            },
            {
                "AbbrNo": "2", 
                "Name": "Jane Smith",
                "SendMode": "Mail",
                "SMBAddress": "",
                "SMBFolder": "",
                "SMBLoginUser": "",
                "SMBLoginPassword": "",
                "SearchKey": "Jkl",
                "UseReferLicence": "Level",
                "ReferGroupNo": "0", 
                "ReferPossibleLevel": "0",
                "WellUse": "No",
                "Pinyin": "No"
            }
        ]
    
    def create_session(self, username, password):
        """Create a new session"""
        # Simple auth check
        if username == "AdminAdmin" and password == "1234567812345678":
            session_id = str(uuid.uuid4())
            h_token = str(uuid.uuid4())
            self.sessions[session_id] = {
                "username": username,
                "created_at": time.time(),
                "authenticated": True
            }
            self.h_tokens[session_id] = h_token
            return session_id, h_token
        return None, None
    
    def validate_session(self, session_id):
        """Check if session is valid"""
        return session_id in self.sessions and self.sessions[session_id]["authenticated"]
    
    def get_h_token(self, session_id):
        """Get h_token for session"""
        return self.h_tokens.get(session_id)
    
    def create_export_job(self, session_id):
        """Create an export job"""
        if not self.validate_session(session_id):
            return None
        
        job_id = str(uuid.uuid4())
        self.jobs[job_id] = {
            "type": "export",
            "status": "running",
            "created_at": time.time(),
            "session_id": session_id
        }
        return job_id
    
    def create_import_job(self, session_id):
        """Create an import job"""
        if not self.validate_session(session_id):
            return None
            
        job_id = str(uuid.uuid4())
        self.jobs[job_id] = {
            "type": "import", 
            "status": "running",
            "created_at": time.time(),
            "session_id": session_id
        }
        return job_id
    
    def get_job_status(self, job_id):
        """Get job status - simulate completion after 10 seconds"""
        if job_id not in self.jobs:
            return None
        
        job = self.jobs[job_id]
        elapsed = time.time() - job["created_at"]
        
        if elapsed > 10:  # Job completes after 10 seconds
            job["status"] = "completed"
        
        return job
    
    def export_address_book(self):
        """Export address book to TSV format"""
        lines = []
        
        # Add metadata
        lines.append("# Generated by Mock Konica Printer")
        lines.append(f"# Export Time: {datetime.now()}")
        lines.append("")
        
        # Add header
        header = [
            "AbbrNo", "Name", "SendMode", "SMBAddress", "SMBFolder",
            "SMBLoginUser", "SMBLoginPassword", "SearchKey", "UseReferLicence",
            "ReferGroupNo", "ReferPossibleLevel", "WellUse", "Pinyin"
        ]
        lines.append("\t".join(header))
        
        # Add data
        for entry in self.address_book:
            row = [entry.get(col, "") for col in header]
            lines.append("\t".join(row))
        
        lines.append("@End")
        
        # Create temporary file
        temp_file = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt', encoding='utf-16-le')
        temp_file.write("\n".join(lines))
        temp_file.close()
        
        # Store with token
        token = str(uuid.uuid4())
        self.exported_files[token] = temp_file.name
        
        return token
    
    def delete_address_item(self, item_id):
        """Delete an address book item by AbbrNo"""
        self.address_book = [item for item in self.address_book if item.get("AbbrNo") != item_id]
        return True

# Global printer instance
printer = MockPrinter()
current_job_id = None

@app.route('/wcd/login.cgi', methods=['POST'])
def login():
    """Handle login requests"""
    username = request.form.get('username')
    password = request.form.get('password')
    
    print(f"[MOCK] Login attempt: {username}")
    
    session_id, h_token = printer.create_session(username, password)
    
    if session_id:
        # Response where <Item> text is 200 (so check_response returns 200)
        response = make_response(
            '<?xml version="1.0" encoding="UTF-8"?>'
            '<Response><Message><Item Code="200">200</Item></Message></Response>'
        )
        response.set_cookie('ID', session_id, domain=request.host.split(':')[0])
        print(f"[MOCK] Login successful for {username}, session: {session_id}")
        return response
    else:
        # Authentication failed
        response = make_response(
            '<?xml version="1.0" encoding="UTF-8"?>'
            '<Response><Message><Item Code="401">Authentication failed</Item></Message></Response>'
        )
        print(f"[MOCK] Login failed for {username}")
        return response


@app.route('/wcd/a_user.cgi', methods=['POST'])
def logout():
    """Handle logout requests"""
    session_id = request.cookies.get('ID')
    
    if session_id and session_id in printer.sessions:
        del printer.sessions[session_id]
        if session_id in printer.h_tokens:
            del printer.h_tokens[session_id]
        print(f"[MOCK] Logout successful for session: {session_id}")
        return '<?xml version="1.0" encoding="UTF-8"?><Response><Message><Item Code="200">Logout successful</Item></Message></Response>'
    
    return '<?xml version="1.0" encoding="UTF-8"?><Response><Message><Item Code="400">No valid session</Item></Message></Response>'

@app.route('/wcd/a_system_impexp.json')
def get_initial_token():
    """Get initial h_token"""
    session_id = request.cookies.get('ID')
    
    if not printer.validate_session(session_id):
        return jsonify({"error": "Invalid session"}), 401
    
    h_token = printer.get_h_token(session_id)
    
    response = {
        "MFP": {
            "Token": h_token
        }
    }
    
    print(f"[MOCK] Provided h_token: {h_token}")
    return jsonify(response)

@app.route('/wcd/api/AppReqSetCustomMessage/_000_002_IMP007', methods=['POST'])
def request_export():
    """Handle export request"""
    global current_job_id
    
    session_id = request.cookies.get('ID')
    if not printer.validate_session(session_id):
        return jsonify({"error": "Invalid session"}), 401
    
    current_job_id = printer.create_export_job(session_id)
    
    response = {
        "MFP": {
            "Message": {
                "Item": {
                    "@Code": "DeviceExportExec",
                    "#text": "Export started"
                }
            }
        }
    }
    
    print(f"[MOCK] Export job started: {current_job_id}")
    return jsonify(response)

@app.route('/wcd/api/AppReqSetCustomMessage/_000_002_IMP008', methods=['POST'])
def request_import():
    """Handle import request"""
    global current_job_id
    
    session_id = request.cookies.get('ID')
    if not printer.validate_session(session_id):
        return jsonify({"error": "Invalid session"}), 401
    
    # Handle file upload
    uploaded_file = request.files.get('AS_ADD_F_FIL')
    if uploaded_file:
        # Save uploaded file temporarily 
        temp_path = tempfile.mktemp(suffix='.txt')
        uploaded_file.save(temp_path)
        print(f"[MOCK] Import file uploaded: {temp_path}")
        
        # Parse the uploaded address book (simplified)
        try:
            with open(temp_path, 'rb') as f:
                content = f.read().decode('utf-16-le', errors='ignore')
            
            lines = content.splitlines()
            
            # Find header and parse entries
            header_found = False
            new_entries = []
            
            for line in lines:
                if line.startswith('AbbrNo\t'):
                    header_found = True
                    header = line.split('\t')
                    continue
                    
                if header_found and line.strip() and not line.startswith('@End'):
                    values = line.split('\t')
                    if len(values) >= len(header):
                        entry = {header[i]: values[i] for i in range(len(header))}
                        new_entries.append(entry)
            
            # Update address book (replace existing entries)
            printer.address_book = new_entries
            print(f"[MOCK] Address book updated with {len(new_entries)} entries")
            
        except Exception as e:
            print(f"[MOCK] Error parsing import file: {e}")
        
        finally:
            os.unlink(temp_path)
    
    current_job_id = printer.create_import_job(session_id)
    
    response = {
        "MFP": {
            "RedirectUrl": "progress"
        }
    }
    
    print(f"[MOCK] Import job started: {current_job_id}")
    return jsonify(response)

@app.route('/wcd/progress', methods=['GET', 'POST'])
def get_progress():
    """Get job progress"""
    if not current_job_id:
        return jsonify({
            "MFP": {
                "Message": {
                    "Item": {
                        "@Code": "NoJob",
                        "#text": "No active job"
                    }
                }
            }
        })
    
    job = printer.get_job_status(current_job_id)
    if not job:
        return jsonify({"error": "Job not found"}), 404
    
    if job["status"] == "running":
        if job["type"] == "export":
            response = {
                "MFP": {
                    "Message": {
                        "Item": {
                            "@Code": "DeviceExportExec", 
                            "#text": "Export in progress"
                        }
                    }
                }
            }
        else:  # import
            response = {
                "MFP": {
                    "Message": {
                        "Item": {
                            "@Code": "DeviceImportExec",
                            "#text": "Import in progress"
                        }
                    },
                    "RedirectUrl": "progress"
                }
            }
    else:  # completed
        if job["type"] == "export":
            response = {
                "MFP": {
                    "Message": {
                        "Item": {
                            "@Code": "Ok_1",
                            "#text": "ReadyToDownload"
                        }
                    }
                }
            }
        else:  # import
            response = {
                "MFP": {
                    "Message": {
                        "Item": {
                            "@Code": "Ok_1", 
                            "#text": "Import completed"
                        }
                    }
                }
            }
    
    return jsonify(response)

@app.route('/wcd/api/AppReqGetCustomData/_000_002_IMP017')
def get_download_token():
    """Get download token after export completion"""
    session_id = request.cookies.get('ID')
    if not printer.validate_session(session_id):
        return jsonify({"error": "Invalid session"}), 401
    
    # Generate export file
    token = printer.export_address_book()
    
    response = {
        "MFP": {
            "Token": token
        }
    }
    
    print(f"[MOCK] Download token generated: {token}")
    return jsonify(response)

@app.route('/wcd/a_filedownload')
def download_file():
    """Download exported file"""
    token = request.args.get('h_token')
    
    if not token or token not in printer.exported_files:
        return "File not found", 404
    
    file_path = printer.exported_files[token]
    
    print(f"[MOCK] Downloading file: {file_path}")
    return send_file(file_path, as_attachment=True, download_name='address_book.txt')

@app.route('/wcd/api/AppReqSetCustomMessage/_007_000_ABR000', methods=['GET'])
def delete_address_item():
    """Delete address book item"""
    session_id = request.cookies.get('ID')
    if not printer.validate_session(session_id):
        return jsonify({"error": "Invalid session"}), 401
    
    item_id = request.args.get('AC_ABR_H_NUM')
    if item_id:
        success = printer.delete_address_item(item_id)
        if success:
            print(f"[MOCK] Deleted address item: {item_id}")
            return jsonify({"status": "success"})
    
    return jsonify({"error": "Item not found"}), 404

@app.route('/status')
def status():
    """Get printer status"""
    return jsonify({
        "status": "online",
        "model": "Mock Konica Bizhub", 
        "address_book_entries": len(printer.address_book),
        "active_sessions": len(printer.sessions)
    })

if __name__ == '__main__':
    print("🖨️  Starting Mock Konica Printer Server")
    print("📋 Default credentials: admin/admin")
    print("🌐 Running on http://127.0.0.1:5000")
    print("📚 Address book starts with sample entries")
    print("\nTo test with your tool:")
    print("1. Update config/printers.py: {'ip': '127.0.0.1:5000'}")
    print("2. Run: make run")
    
    app.run(host='0.0.0.0', port=5000, debug=True)